### ISSUE TITLE
AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [ritheshkumar95/im2latex-tensorflow#26]
Hi all,

I am having difficulty running the predict script. I think it is an error stemming from which distribution you use for tensorflow. I tried upgrading to the most recent version of tensorflow (2.3.0) but got this error still. Here is the issue again in Tensorflow. I am not sure if it is a matter of calling a separate TF function for better im2latex implementation or if it is a problem that must be solved on the tensorflow side of things. Or maybe im2latex needs to be updated to work with the latest version of tensorflow. Just curious! Seems like a cool project!

I am using Windows 10 and PyCharm 2018.2

Tensorflow issue:
https://github.com/tensorflow/nmt/issues/466

Traceback (most recent call last):
  File "C:/Users/Owner/AppData/Local/Programs/Python/Python37/Lib/site-packages/im2latex_tensorflow/im2latex_tensorflow_master/predict.py", line 4, in <module>
    import tflib.ops
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37\Lib\site-packages\im2latex_tensorflow\im2latex_tensorflow_master\tflib\ops.py", line 251, in <module>
    class GRUCell(tf.nn.rnn_cell.RNNCell):
AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell'

**Comment by yang-stressfree** [comment]
Consider this is a 3 years ago project, so maybe try tensorflow 1.X.
